trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: FileTransform@1
  displayName: 'Substitute variables'
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)'
    fileType: 'json'
    targetFiles: '**/appsettings.json'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    zipAfterPublish: true

- task: AzureWebApp@1
  displayName: 'Deployment'
  inputs:
    azureSubscription: 'Azure for Students(6d415483-a70c-4647-8151-352a0dba5021)'
    appType: 'webApp'
    appName: 'recaller-bot'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'

# - task: AzureRmWebAppDeployment@4
#   inputs:
#     ConnectionType: 'AzureRM'
#     azureSubscription: 'Azure for Students(6d415483-a70c-4647-8151-352a0dba5021)'
#     appType: 'webApp'
#     WebAppName: 'recaller-bot'